# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - <<: &build_defaults
      binary: bin/s3select
      main: ./cmd/s3select
      ldflags:
        - -s -w -X github.com/44smkn/s3select/pkg/build.Version={{.Version}} -X github.com/44smkn/s3select/pkg/build.Date={{time "2006-01-02"}}
    id: macos
    goos: [darwin]
    goarch: [amd64]

  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: [amd64, arm64]
    env:
      - CGO_ENABLED=0

archives:
  - id: nix
    builds: [macos, linux]
    <<: &archive_defaults
      name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    replacements:
      darwin: macOS
    format: tar.gz
    files:
      - LICENSE
